### ISSUE TITLE
I'm unable to start on localhost when I type yarn start, it shows error

### ISSUE THREAD

**Issue by Durand98** [themesberg/volt-react-dashboard#36]
PS C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master> yarn start
yarn run v1.22.21
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master\node_modules\webpack\lib\util\createHash.js:135:53)       
    at NormalModule._initBuildHash (C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master\node_modules\webpack\lib\NormalModule.js:417:
16)
    at handleParseError (C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master\node_modules\webpack\lib\NormalModule.js:471:10)        
    at C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master\node_modules\loader-runner\lib\LoaderRunner.js:214:1
0)
    at iterateNormalLoaders (C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master\node_modules\loader-runner\lib\LoaderRunner.js:221:1
0)
C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master\node_modules\webpack\lib\util\createHash.js:135:53)       
    at NormalModule._initBuildHash (C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master\node_modules\webpack\lib\NormalModule.js:417:
16)
    at C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master\node_modules\loader-runner\lib\LoaderRunner.js:111:13)  
    at C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master\node_modules\react-scripts\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.11.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\Durand\Downloads\traiter\volt-react-dashboard-master>

**Comment by MandeepSingh1** [comment]
Go to the Package.json file and change the start command under the script tag. After this, your code will run. I also faced the same issue and fixed it using the below command. Don't do anything.

`"start": "react-scripts --openssl-legacy-provider start",`
